In [ ]:
pip install pandas

In [180]:
import pandas as pd
import numpy as np

In [181]:
# Show all rows and columns without truncation
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [182]:
# Importing dataframes
bacteria_path = 'https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/bacteria.csv'
bacteria_data = pd.read_csv(bacteria_path)
bacteria_data.head(5)

,C1,C2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
2,3.178256,5.519982,A003,Escherichia coli,blood,Commensal strain,1,0.066501,0.498872,0.061445,0.564547,0.313546,0.368546,8
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
4,2.691040,4.057780,A005,Escherichia coli,feces,Commensal strain,1,0.101523,0.272807,0.120601,0.186437,0.121745,0.398072,3

In [183]:
# Part 1: Basic Data Inspection
# Shape of the dataset
print('Shape:') 
bacteria_data.shape

Shape:

(50, 14)

In [184]:
# List of all column names
print('Columns:')
bacteria_data.columns.tolist()

Columns:

['C1',
 'C2',
 'sample_id',
 'species',
 'Isolation origin',
 'Phenotype',
 'BSL',
 'soln',
 'carb_fit',
 'cipro_fit',
 'genta_fit',
 'kan_fit',
 'pip_fit',
 'labels']

In [185]:
# Part 2: Data Selection
# Select row 15
print('Row 15:')
bacteria_data.iloc[15]

Row 15:

C1                           7.538784
C2                           6.070635
sample_id                        A016
species              Escherichia coli
Isolation origin                urine
Phenotype           Pathogenic strain
BSL                                 2
soln                          0.07272
carb_fit                      0.93776
cipro_fit                    0.068781
genta_fit                    0.423892
kan_fit                      0.047651
pip_fit                      0.923642
labels                              1
Name: 15, dtype: object

In [186]:
# Select the column species
print('Column species:')
bacteria_data[['species']]

Column species:

             species
0   Escherichia coli
1   Escherichia coli
2   Escherichia coli
3   Escherichia coli
4   Escherichia coli
5   Escherichia coli
6   Escherichia coli
7   Escherichia coli
8   Escherichia coli
9   Escherichia coli
10  Escherichia coli
11  Escherichia coli
12  Escherichia coli
13  Escherichia coli
14  Escherichia coli
15  Escherichia coli
16  Escherichia coli
17  Escherichia coli
18  Escherichia coli
19  Escherichia coli
20  Escherichia coli
21  Escherichia coli
22  Escherichia coli
23  Escherichia coli
24  Escherichia coli
25  Escherichia coli
26  Escherichia coli
27  Escherichia coli
28  Escherichia coli
29  Escherichia coli
30  Escherichia coli
31  Escherichia coli
32  Escherichia coli
33  Escherichia coli
34  Escherichia coli
35  Escherichia coli
36  Escherichia coli
37  Escherichia coli
38  Escherichia coli
39  Escherichia coli
40  Escherichia coli
41  Escherichia coli
42  Escherichia coli
43  Escherichia coli
44  Escherichia coli
45  Escherichia coli
46  Escherichia coli
47  Escherichia coli
48  Escherichia coli
49  Escherichia coli

In [187]:
# Retrieve the value at row 15 for the column Isolation origin
print('Value at row 15, Isolation origin:')
bacteria_data.loc[15, 'Isolation origin']

Value at row 15, Isolation origin:

'urine'

In [188]:
# Part 3: Data Filtering
# Show only rows (genes) where carb_fit is greater than 0.5
print('Rows where carb_fit > 0.5:')
bacteria_data[bacteria_data['carb_fit'] > 0.5]

Rows where carb_fit > 0.5:

,C1,C2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
7,6.423557,8.646023,A008,Escherichia coli,blood,Commensal strain,1,0.097187,1.166485,0.095053,0.669338,0.333712,1.242928,5
8,3.903013,6.026175,A009,Escherichia coli,feces,Commensal strain,1,NaN,0.847180,0.051094,0.518218,0.127822,0.548859,2
11,2.120512,3.840546,A012,Escherichia coli,animal,Commensal strain,1,0.199173,1.395184,0.164683,0.579315,0.202552,1.442600,3
12,5.605287,8.474524,A013,Escherichia coli,animal,Commensal strain,2,0.028711,1.005421,0.029881,0.519286,0.102004,0.956556,7
13,8.125718,6.337743,A014,Escherichia coli,animal,Commensal strain,1,0.040533,1.257316,0.033206,0.573845,0.167805,1.242958,1
14,5.373610,6.328361,A015,Escherichia coli,feces,Commensal strain,1,0.228693,1.327152,0.225516,0.722939,0.429100,1.258443,2
15,7.538784,6.070635,A016,Escherichia coli,urine,Pathogenic strain,2,0.072720,0.937760,0.068781,0.423892,0.047651,0.923642,1
16,2.329631,6.700236,A017,Escherichia coli,animal,Commensal strain,1,0.110548,1.289325,0.110910,0.659531,0.339610,1.570828,6
17,5.642871,4.021120,A018,Escherichia coli,blood,Commensal strain,1,0.059517,1.287046,0.058336,0.518358,0.326629,1.497189,0
18,4.623605,6.560728,A019,Escherichia coli,urine,Commensal strain,2,0.125819,1.257749,0.121310,0.505074,0.085845,1.423255,2
19,8.049274,5.591848,A020,Escherichia coli,animal,Pathogenic strain,2,0.082608,1.442216,0.085339,0.623049,0.475105,1.357744,1
20,2.310514,4.258615,A021,Escherichia coli,urine,Pathogenic strain,2,0.061584,0.950317,0.075575,0.313006,0.162490,0.894661,3
21,7.502212,6.049275,A022,Escherichia coli,urine,Pathogenic strain,2,0.101257,1.376189,0.098314,0.589933,0.203312,1.252159,1
24,5.788682,4.119866,A025,Escherichia coli,urine,Pathogenic strain,2,0.116096,1.069537,0.105668,0.409785,0.086824,1.458853,0
26,7.637985,6.490184,A027,Escherichia coli,animal,Commensal strain,1,0.040250,1.407527,0.040860,0.584192,0.000000,1.490921,1
30,3.480180,5.646476,A031,Escherichia coli,animal,Commensal strain,1,0.167967,0.617078,0.161436,0.467293,0.392423,0.621435,3
31,5.257375,5.715269,A032,Escherichia coli,blood,Commensal strain,1,1.133788,1.048136,1.119326,0.584882,0.495628,0.709660,2
33,5.388848,8.466379,A034,Escherichia coli,urine,Pathogenic strain,2,0.148468,1.514931,0.174638,0.964351,0.281844,1.799167,7
35,6.915292,6.583098,A036,Escherichia coli,urine,Pathogenic strain,2,0.061489,0.847877,0.065874,0.474316,0.135198,1.276985,4
36,6.638712,5.152672,A037,Escherichia coli,animal,Commensal strain,1,0.000000,1.123975,0.000000,0.570495,0.000000,1.310924,9
38,6.772678,7.540791,A039,Escherichia coli,animal,Commensal strain,1,NaN,1.017625,0.852120,0.986102,1.471669,1.512971,4
40,7.452787,6.422853,A041,Escherichia coli,animal,Commensal strain,1,0.090609,1.060518,0.075027,0.619777,0.614616,0.849139,1
41,6.832757,7.503795,A042,Escherichia coli,animal,Commensal strain,2,0.063002,1.099966,0.059168,0.698869,0.468158,1.496427,4
42,5.142991,4.475378,A043,Escherichia coli,animal,Commensal strain,1,0.027601,1.143011,0.024973,0.587101,0.412273,1.441764,0
43,4.572856,3.687471,A044,Escherichia coli,animal,Commensal strain,1,0.046493,1.085507,0.043165,0.516218,0.311859,1.140670,0
44,6.550695,5.065118,A045,Escherichia coli,animal,Commensal strain,1,0.028830,1.370487,0.015348,0.751111,0.262701,1.571381,9
46,5.020254,8.567518,A047,Escherichia coli,blood,Pathogenic strain,2,0.059151,0.768701,0.053085,0.386740,0.062916,0.721458,7
48,5.112294,3.986432,A049,Escherichia coli,blood,Commensal strain,2,0.068078,1.466022,0.065118,0.484535,0.000000,1.634570,0

In [189]:
# Part 4: Handling Missing Data
# Create a copy of bacteria_data as bacteria_data_missing
bacteria_data_missing = bacteria_data.copy()

# Count the number of missing values per row
print('Missing values per row:')
bacteria_data_missing.isna().sum(axis=1)

Missing values per row:

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    1
39    1
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
dtype: int64

In [190]:
# Create a new version of the dataset where missing values are filled with 1
print('Dataset with missing values filled with 1:')
bacteria_data_missing.fillna(1)

Dataset with missing values filled with 1:

,C1,C2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
2,3.178256,5.519982,A003,Escherichia coli,blood,Commensal strain,1,0.066501,0.498872,0.061445,0.564547,0.313546,0.368546,8
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
4,2.691040,4.057780,A005,Escherichia coli,feces,Commensal strain,1,0.101523,0.272807,0.120601,0.186437,0.121745,0.398072,3
5,8.601402,5.937885,A006,Escherichia coli,blood,Commensal strain,2,0.059154,0.440163,0.055266,0.626941,0.399951,0.318405,1
6,7.017246,8.315863,A007,Escherichia coli,feces,Commensal strain,1,0.065956,0.410300,0.072963,0.665995,0.000000,0.682995,5
7,6.423557,8.646023,A008,Escherichia coli,blood,Commensal strain,1,0.097187,1.166485,0.095053,0.669338,0.333712,1.242928,5
8,3.903013,6.026175,A009,Escherichia coli,feces,Commensal strain,1,1.000000,0.847180,0.051094,0.518218,0.127822,0.548859,2
9,5.572557,5.726862,A010,Escherichia coli,feces,Commensal strain,1,0.049851,0.307426,0.053692,0.656571,0.669971,0.544498,2
10,6.978213,5.417409,A011,Escherichia coli,urine,Pathogenic strain,2,0.066525,0.360219,0.057416,0.330000,0.042813,0.207323,9
11,2.120512,3.840546,A012,Escherichia coli,animal,Commensal strain,1,0.199173,1.395184,0.164683,0.579315,0.202552,1.442600,3
12,5.605287,8.474524,A013,Escherichia coli,animal,Commensal strain,2,0.028711,1.005421,0.029881,0.519286,0.102004,0.956556,7
13,8.125718,6.337743,A014,Escherichia coli,animal,Commensal strain,1,0.040533,1.257316,0.033206,0.573845,0.167805,1.242958,1
14,5.373610,6.328361,A015,Escherichia coli,feces,Commensal strain,1,0.228693,1.327152,0.225516,0.722939,0.429100,1.258443,2
15,7.538784,6.070635,A016,Escherichia coli,urine,Pathogenic strain,2,0.072720,0.937760,0.068781,0.423892,0.047651,0.923642,1
16,2.329631,6.700236,A017,Escherichia coli,animal,Commensal strain,1,0.110548,1.289325,0.110910,0.659531,0.339610,1.570828,6
17,5.642871,4.021120,A018,Escherichia coli,blood,Commensal strain,1,0.059517,1.287046,0.058336,0.518358,0.326629,1.497189,0
18,4.623605,6.560728,A019,Escherichia coli,urine,Commensal strain,2,0.125819,1.257749,0.121310,0.505074,0.085845,1.423255,2
19,8.049274,5.591848,A020,Escherichia coli,animal,Pathogenic strain,2,0.082608,1.442216,0.085339,0.623049,0.475105,1.357744,1
20,2.310514,4.258615,A021,Escherichia coli,urine,Pathogenic strain,2,0.061584,0.950317,0.075575,0.313006,0.162490,0.894661,3
21,7.502212,6.049275,A022,Escherichia coli,urine,Pathogenic strain,2,0.101257,1.376189,0.098314,0.589933,0.203312,1.252159,1
22,3.740108,4.893625,A023,Escherichia coli,animal,Commensal strain,1,0.101257,0.407429,0.077279,0.661731,0.487289,0.412373,8
23,4.709624,4.452234,A024,Escherichia coli,blood,Commensal strain,1,0.055793,0.449640,0.053833,0.571760,0.243998,0.817029,0
24,5.788682,4.119866,A025,Escherichia coli,urine,Pathogenic strain,2,0.116096,1.069537,0.105668,0.409785,0.086824,1.458853,0
25,6.135004,7.595472,A026,Escherichia coli,urine,Pathogenic strain,2,0.080601,0.402158,0.077426,0.414082,0.103131,0.519733,7
26,7.637985,6.490184,A027,Escherichia coli,animal,Commensal strain,1,0.040250,1.407527,0.040860,0.584192,0.000000,1.490921,1
27,7.065422,5.343500,A028,Escherichia coli,urine,Pathogenic strain,2,0.063728,0.469590,0.060516,0.462755,0.241647,0.335668,9
28,3.780450,5.376362,A029,Escherichia coli,urine,Pathogenic strain,2,0.038148,0.454360,0.041360,0.181459,0.063350,0.410762,8
29,3.714443,5.799578,A030,Escherichia coli,blood,Commensal strain,1,0.076548,0.398078,0.071058,0.736091,0.653928,0.365928,6
30,3.480180,5.646476,A031,Escherichia coli,animal,Commensal strain,1,0.167967,0.617078,0.161436,0.467293,0.392423,0.621435,3
31,5.257375,5.715269,A032,Escherichia coli,blood,Commensal strain,1,1.133788,1.048136,1.119326,0.584882,0.495628,0.709660,2
32,8.455470,6.502862,A033,Escherichia coli,animal,Commensal strain,1,0.045629,0.282114,0.053033,1.034223,0.746827,0.224086,1
33,5.388848,8.466379,A034,Escherichia coli,urine,Pathogenic strain,2,0.148468,1.514931,0.174638,0.964351,0.281844,1.799167,7
34,4.657805,5.734182,A035,Escherichia coli,blood,Pathogenic strain,2,0.090453,0.358145,0.091277,0.602020,0.128149,0.356802,9
35,6.915292,6.583098,A036,Escherichia coli,urine,Pathogenic strain,2,0.061489,0.847877,0.065874,0.474316,0.135198,1.276985,4
36,6.638712,5.152672,A037,Escherichia coli,animal,Commensal strain,1,0.000000,1.123975,0.000000,0.570495,0.000000,1.310924,9
37,2.637517,4.127516,A038,Escherichia coli,animal,Commensal strain,1,0.064158,0.361581,0.054835,0.848437,0.866862,0.264537,3
38,6.772678,7.540791,A039,Escherichia coli,animal,Commensal strain,1,1.000000,1.017625,0.852120,0.986102,1.471669,1.512971,4
39,2.754321,5.394068,A040,Escherichia coli,animal,Commensal strain,1,1.000000,0.474561,0.000000,0.418395,0.000000,0.756904,6
40,7.452787,6.422853,A041,Escherichia coli,animal,Commensal strain,1,0.090609,1.060518,0.075027,0.619777,0.614616,0.849139,1
41,6.832757,7.503795,A042,Escherichia coli,animal,Commensal strain,2,0.063002,1.099966,0.059168,0.698869,0.468158,1.496427,4
42,5.142991,4.475378,A043,Escherichia coli,animal,Commensal strain,1,0.027601,1.143011,0.024973,0.587101,0.412273,1.441764,0
43,4.572856,3.687471,A044,Escherichia coli,animal,Commensal strain,1,0.046493,1.085507,0.043165,0.516218,0.311859,1.140670,0
44,6.550695,5.065118,A045,Escherichia coli,animal,Commensal strain,1,0.028830,1.370487,0.015348,0.751111,0.262701,1.571381,9
45,4.764575,6.896369,A046,Escherichia coli,blood,Commensal strain,1,0.038908,0.200962,0.036836,0.528246,0.164302,0.463759,2
46,5.020254,8.567518,A047,Escherichia coli,blood,Pathogenic strain,2,0.059151,0.768701,0.053085,0.386740,0.062916,0.721458,7
47,3.021666,7.141584,A048,Escherichia coli,urine,Pathogenic strain,2,0.000000,0.295724,0.000000,0.000000,0.000000,0.000000,6
48,5.112294,3.986432,A049,Escherichia coli,blood,Commensal strain,2,0.068078,1.466022,0.065118,0.484535,0.000000,1.634570,0
49,6.964060,6.230907,A050,Escherichia coli,blood,Pathogenic strain,2,0.085828,0.498012,0.085823,0.406485,0.400230,0.804463,1

In [191]:
# Create another version where columns containing missing values are dropped entirely
print('Dataset with columns containing missing values dropped:')
bacteria_data_missing.dropna()

Dataset with columns containing missing values dropped:

,C1,C2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
2,3.178256,5.519982,A003,Escherichia coli,blood,Commensal strain,1,0.066501,0.498872,0.061445,0.564547,0.313546,0.368546,8
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
4,2.691040,4.057780,A005,Escherichia coli,feces,Commensal strain,1,0.101523,0.272807,0.120601,0.186437,0.121745,0.398072,3
5,8.601402,5.937885,A006,Escherichia coli,blood,Commensal strain,2,0.059154,0.440163,0.055266,0.626941,0.399951,0.318405,1
6,7.017246,8.315863,A007,Escherichia coli,feces,Commensal strain,1,0.065956,0.410300,0.072963,0.665995,0.000000,0.682995,5
7,6.423557,8.646023,A008,Escherichia coli,blood,Commensal strain,1,0.097187,1.166485,0.095053,0.669338,0.333712,1.242928,5
9,5.572557,5.726862,A010,Escherichia coli,feces,Commensal strain,1,0.049851,0.307426,0.053692,0.656571,0.669971,0.544498,2
10,6.978213,5.417409,A011,Escherichia coli,urine,Pathogenic strain,2,0.066525,0.360219,0.057416,0.330000,0.042813,0.207323,9
11,2.120512,3.840546,A012,Escherichia coli,animal,Commensal strain,1,0.199173,1.395184,0.164683,0.579315,0.202552,1.442600,3
12,5.605287,8.474524,A013,Escherichia coli,animal,Commensal strain,2,0.028711,1.005421,0.029881,0.519286,0.102004,0.956556,7
13,8.125718,6.337743,A014,Escherichia coli,animal,Commensal strain,1,0.040533,1.257316,0.033206,0.573845,0.167805,1.242958,1
14,5.373610,6.328361,A015,Escherichia coli,feces,Commensal strain,1,0.228693,1.327152,0.225516,0.722939,0.429100,1.258443,2
15,7.538784,6.070635,A016,Escherichia coli,urine,Pathogenic strain,2,0.072720,0.937760,0.068781,0.423892,0.047651,0.923642,1
16,2.329631,6.700236,A017,Escherichia coli,animal,Commensal strain,1,0.110548,1.289325,0.110910,0.659531,0.339610,1.570828,6
17,5.642871,4.021120,A018,Escherichia coli,blood,Commensal strain,1,0.059517,1.287046,0.058336,0.518358,0.326629,1.497189,0
18,4.623605,6.560728,A019,Escherichia coli,urine,Commensal strain,2,0.125819,1.257749,0.121310,0.505074,0.085845,1.423255,2
19,8.049274,5.591848,A020,Escherichia coli,animal,Pathogenic strain,2,0.082608,1.442216,0.085339,0.623049,0.475105,1.357744,1
20,2.310514,4.258615,A021,Escherichia coli,urine,Pathogenic strain,2,0.061584,0.950317,0.075575,0.313006,0.162490,0.894661,3
21,7.502212,6.049275,A022,Escherichia coli,urine,Pathogenic strain,2,0.101257,1.376189,0.098314,0.589933,0.203312,1.252159,1
22,3.740108,4.893625,A023,Escherichia coli,animal,Commensal strain,1,0.101257,0.407429,0.077279,0.661731,0.487289,0.412373,8
23,4.709624,4.452234,A024,Escherichia coli,blood,Commensal strain,1,0.055793,0.449640,0.053833,0.571760,0.243998,0.817029,0
24,5.788682,4.119866,A025,Escherichia coli,urine,Pathogenic strain,2,0.116096,1.069537,0.105668,0.409785,0.086824,1.458853,0
25,6.135004,7.595472,A026,Escherichia coli,urine,Pathogenic strain,2,0.080601,0.402158,0.077426,0.414082,0.103131,0.519733,7
26,7.637985,6.490184,A027,Escherichia coli,animal,Commensal strain,1,0.040250,1.407527,0.040860,0.584192,0.000000,1.490921,1
27,7.065422,5.343500,A028,Escherichia coli,urine,Pathogenic strain,2,0.063728,0.469590,0.060516,0.462755,0.241647,0.335668,9
28,3.780450,5.376362,A029,Escherichia coli,urine,Pathogenic strain,2,0.038148,0.454360,0.041360,0.181459,0.063350,0.410762,8
29,3.714443,5.799578,A030,Escherichia coli,blood,Commensal strain,1,0.076548,0.398078,0.071058,0.736091,0.653928,0.365928,6
30,3.480180,5.646476,A031,Escherichia coli,animal,Commensal strain,1,0.167967,0.617078,0.161436,0.467293,0.392423,0.621435,3
31,5.257375,5.715269,A032,Escherichia coli,blood,Commensal strain,1,1.133788,1.048136,1.119326,0.584882,0.495628,0.709660,2
32,8.455470,6.502862,A033,Escherichia coli,animal,Commensal strain,1,0.045629,0.282114,0.053033,1.034223,0.746827,0.224086,1
33,5.388848,8.466379,A034,Escherichia coli,urine,Pathogenic strain,2,0.148468,1.514931,0.174638,0.964351,0.281844,1.799167,7
34,4.657805,5.734182,A035,Escherichia coli,blood,Pathogenic strain,2,0.090453,0.358145,0.091277,0.602020,0.128149,0.356802,9
35,6.915292,6.583098,A036,Escherichia coli,urine,Pathogenic strain,2,0.061489,0.847877,0.065874,0.474316,0.135198,1.276985,4
36,6.638712,5.152672,A037,Escherichia coli,animal,Commensal strain,1,0.000000,1.123975,0.000000,0.570495,0.000000,1.310924,9
37,2.637517,4.127516,A038,Escherichia coli,animal,Commensal strain,1,0.064158,0.361581,0.054835,0.848437,0.866862,0.264537,3
40,7.452787,6.422853,A041,Escherichia coli,animal,Commensal strain,1,0.090609,1.060518,0.075027,0.619777,0.614616,0.849139,1
41,6.832757,7.503795,A042,Escherichia coli,animal,Commensal strain,2,0.063002,1.099966,0.059168,0.698869,0.468158,1.496427,4
42,5.142991,4.475378,A043,Escherichia coli,animal,Commensal strain,1,0.027601,1.143011,0.024973,0.587101,0.412273,1.441764,0
43,4.572856,3.687471,A044,Escherichia coli,animal,Commensal strain,1,0.046493,1.085507,0.043165,0.516218,0.311859,1.140670,0
44,6.550695,5.065118,A045,Escherichia coli,animal,Commensal strain,1,0.028830,1.370487,0.015348,0.751111,0.262701,1.571381,9
45,4.764575,6.896369,A046,Escherichia coli,blood,Commensal strain,1,0.038908,0.200962,0.036836,0.528246,0.164302,0.463759,2
46,5.020254,8.567518,A047,Escherichia coli,blood,Pathogenic strain,2,0.059151,0.768701,0.053085,0.386740,0.062916,0.721458,7
47,3.021666,7.141584,A048,Escherichia coli,urine,Pathogenic strain,2,0.000000,0.295724,0.000000,0.000000,0.000000,0.000000,6
48,5.112294,3.986432,A049,Escherichia coli,blood,Commensal strain,2,0.068078,1.466022,0.065118,0.484535,0.000000,1.634570,0
49,6.964060,6.230907,A050,Escherichia coli,blood,Pathogenic strain,2,0.085828,0.498012,0.085823,0.406485,0.400230,0.804463,1

In [192]:
# Part 5: Checking Missing Data in Main Dataset
# Check whether missing values exist
print('Missing values per column in bacteria_data:')
bacteria_data_missing.isna().sum()

Missing values per column in bacteria_data:

C1                  0
C2                  0
sample_id           0
species             0
Isolation origin    0
Phenotype           0
BSL                 0
soln                3
carb_fit            0
cipro_fit           0
genta_fit           0
kan_fit             0
pip_fit             0
labels              0
dtype: int64

In [193]:
# If yes, report how many missing values are present (total or per column)
print('Total missing values:', bacteria_data_missing.isna().sum().sum())

Total missing values: 3

In [194]:
# Part 6: Column Renaming
# Rename C1 to UMAP1 and C2 to UMAP2
bacteria_data.rename(columns={'C1': 'UMAP1', 'C2': 'UMAP2'}, inplace=True)
print('Columns after renaming:')
bacteria_data.columns.tolist()

Columns after renaming:

['UMAP1',
 'UMAP2',
 'sample_id',
 'species',
 'Isolation origin',
 'Phenotype',
 'BSL',
 'soln',
 'carb_fit',
 'cipro_fit',
 'genta_fit',
 'kan_fit',
 'pip_fit',
 'labels']

In [195]:
# Confirm as DataFrame
print('Confirming DataFrame:')
bacteria_data.head()

Confirming DataFrame:

,UMAP1,UMAP2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
2,3.178256,5.519982,A003,Escherichia coli,blood,Commensal strain,1,0.066501,0.498872,0.061445,0.564547,0.313546,0.368546,8
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
4,2.691040,4.057780,A005,Escherichia coli,feces,Commensal strain,1,0.101523,0.272807,0.120601,0.186437,0.121745,0.398072,3

In [196]:
# Part 7: Sorting
# By the column BSL
print('Data sorted by BSL:')
bacteria_data.sort_values(by='BSL')

Data sorted by BSL:

,UMAP1,UMAP2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
16,2.329631,6.700236,A017,Escherichia coli,animal,Commensal strain,1,0.110548,1.289325,0.110910,0.659531,0.339610,1.570828,6
30,3.480180,5.646476,A031,Escherichia coli,animal,Commensal strain,1,0.167967,0.617078,0.161436,0.467293,0.392423,0.621435,3
29,3.714443,5.799578,A030,Escherichia coli,blood,Commensal strain,1,0.076548,0.398078,0.071058,0.736091,0.653928,0.365928,6
26,7.637985,6.490184,A027,Escherichia coli,animal,Commensal strain,1,0.040250,1.407527,0.040860,0.584192,0.000000,1.490921,1
36,6.638712,5.152672,A037,Escherichia coli,animal,Commensal strain,1,0.000000,1.123975,0.000000,0.570495,0.000000,1.310924,9
37,2.637517,4.127516,A038,Escherichia coli,animal,Commensal strain,1,0.064158,0.361581,0.054835,0.848437,0.866862,0.264537,3
23,4.709624,4.452234,A024,Escherichia coli,blood,Commensal strain,1,0.055793,0.449640,0.053833,0.571760,0.243998,0.817029,0
22,3.740108,4.893625,A023,Escherichia coli,animal,Commensal strain,1,0.101257,0.407429,0.077279,0.661731,0.487289,0.412373,8
38,6.772678,7.540791,A039,Escherichia coli,animal,Commensal strain,1,NaN,1.017625,0.852120,0.986102,1.471669,1.512971,4
39,2.754321,5.394068,A040,Escherichia coli,animal,Commensal strain,1,NaN,0.474561,0.000000,0.418395,0.000000,0.756904,6
40,7.452787,6.422853,A041,Escherichia coli,animal,Commensal strain,1,0.090609,1.060518,0.075027,0.619777,0.614616,0.849139,1
17,5.642871,4.021120,A018,Escherichia coli,blood,Commensal strain,1,0.059517,1.287046,0.058336,0.518358,0.326629,1.497189,0
31,5.257375,5.715269,A032,Escherichia coli,blood,Commensal strain,1,1.133788,1.048136,1.119326,0.584882,0.495628,0.709660,2
42,5.142991,4.475378,A043,Escherichia coli,animal,Commensal strain,1,0.027601,1.143011,0.024973,0.587101,0.412273,1.441764,0
32,8.455470,6.502862,A033,Escherichia coli,animal,Commensal strain,1,0.045629,0.282114,0.053033,1.034223,0.746827,0.224086,1
13,8.125718,6.337743,A014,Escherichia coli,animal,Commensal strain,1,0.040533,1.257316,0.033206,0.573845,0.167805,1.242958,1
2,3.178256,5.519982,A003,Escherichia coli,blood,Commensal strain,1,0.066501,0.498872,0.061445,0.564547,0.313546,0.368546,8
4,2.691040,4.057780,A005,Escherichia coli,feces,Commensal strain,1,0.101523,0.272807,0.120601,0.186437,0.121745,0.398072,3
45,4.764575,6.896369,A046,Escherichia coli,blood,Commensal strain,1,0.038908,0.200962,0.036836,0.528246,0.164302,0.463759,2
14,5.373610,6.328361,A015,Escherichia coli,feces,Commensal strain,1,0.228693,1.327152,0.225516,0.722939,0.429100,1.258443,2
7,6.423557,8.646023,A008,Escherichia coli,blood,Commensal strain,1,0.097187,1.166485,0.095053,0.669338,0.333712,1.242928,5
6,7.017246,8.315863,A007,Escherichia coli,feces,Commensal strain,1,0.065956,0.410300,0.072963,0.665995,0.000000,0.682995,5
9,5.572557,5.726862,A010,Escherichia coli,feces,Commensal strain,1,0.049851,0.307426,0.053692,0.656571,0.669971,0.544498,2
44,6.550695,5.065118,A045,Escherichia coli,animal,Commensal strain,1,0.028830,1.370487,0.015348,0.751111,0.262701,1.571381,9
11,2.120512,3.840546,A012,Escherichia coli,animal,Commensal strain,1,0.199173,1.395184,0.164683,0.579315,0.202552,1.442600,3
43,4.572856,3.687471,A044,Escherichia coli,animal,Commensal strain,1,0.046493,1.085507,0.043165,0.516218,0.311859,1.140670,0
8,3.903013,6.026175,A009,Escherichia coli,feces,Commensal strain,1,NaN,0.847180,0.051094,0.518218,0.127822,0.548859,2
41,6.832757,7.503795,A042,Escherichia coli,animal,Commensal strain,2,0.063002,1.099966,0.059168,0.698869,0.468158,1.496427,4
46,5.020254,8.567518,A047,Escherichia coli,blood,Pathogenic strain,2,0.059151,0.768701,0.053085,0.386740,0.062916,0.721458,7
35,6.915292,6.583098,A036,Escherichia coli,urine,Pathogenic strain,2,0.061489,0.847877,0.065874,0.474316,0.135198,1.276985,4
34,4.657805,5.734182,A035,Escherichia coli,blood,Pathogenic strain,2,0.090453,0.358145,0.091277,0.602020,0.128149,0.356802,9
47,3.021666,7.141584,A048,Escherichia coli,urine,Pathogenic strain,2,0.000000,0.295724,0.000000,0.000000,0.000000,0.000000,6
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
24,5.788682,4.119866,A025,Escherichia coli,urine,Pathogenic strain,2,0.116096,1.069537,0.105668,0.409785,0.086824,1.458853,0
28,3.780450,5.376362,A029,Escherichia coli,urine,Pathogenic strain,2,0.038148,0.454360,0.041360,0.181459,0.063350,0.410762,8
27,7.065422,5.343500,A028,Escherichia coli,urine,Pathogenic strain,2,0.063728,0.469590,0.060516,0.462755,0.241647,0.335668,9
25,6.135004,7.595472,A026,Escherichia coli,urine,Pathogenic strain,2,0.080601,0.402158,0.077426,0.414082,0.103131,0.519733,7
48,5.112294,3.986432,A049,Escherichia coli,blood,Commensal strain,2,0.068078,1.466022,0.065118,0.484535,0.000000,1.634570,0
21,7.502212,6.049275,A022,Escherichia coli,urine,Pathogenic strain,2,0.101257,1.376189,0.098314,0.589933,0.203312,1.252159,1
20,2.310514,4.258615,A021,Escherichia coli,urine,Pathogenic strain,2,0.061584,0.950317,0.075575,0.313006,0.162490,0.894661,3
19,8.049274,5.591848,A020,Escherichia coli,animal,Pathogenic strain,2,0.082608,1.442216,0.085339,0.623049,0.475105,1.357744,1
18,4.623605,6.560728,A019,Escherichia coli,urine,Commensal strain,2,0.125819,1.257749,0.121310,0.505074,0.085845,1.423255,2
15,7.538784,6.070635,A016,Escherichia coli,urine,Pathogenic strain,2,0.072720,0.937760,0.068781,0.423892,0.047651,0.923642,1
12,5.605287,8.474524,A013,Escherichia coli,animal,Commensal strain,2,0.028711,1.005421,0.029881,0.519286,0.102004,0.956556,7
10,6.978213,5.417409,A011,Escherichia coli,urine,Pathogenic strain,2,0.066525,0.360219,0.057416,0.330000,0.042813,0.207323,9
5,8.601402,5.937885,A006,Escherichia coli,blood,Commensal strain,2,0.059154,0.440163,0.055266,0.626941,0.399951,0.318405,1
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
33,5.388848,8.466379,A034,Escherichia coli,urine,Pathogenic strain,2,0.148468,1.514931,0.174638,0.964351,0.281844,1.799167,7
49,6.964060,6.230907,A050,Escherichia coli,blood,Pathogenic strain,2,0.085828,0.498012,0.085823,0.406485,0.400230,0.804463,1

In [197]:
# In descending order (highest to lowest)
print('Data sorted by BSL (descending order):')
bacteria_data.sort_values(by='BSL', ascending=False)

Data sorted by BSL (descending order):

,UMAP1,UMAP2,sample_id,species,Isolation origin,Phenotype,BSL,soln,carb_fit,cipro_fit,genta_fit,kan_fit,pip_fit,labels
0,7.895415,6.303232,A001,Escherichia coli,urine,Pathogenic strain,2,0.043922,0.833539,0.040470,0.429654,0.046829,0.857467,1
18,4.623605,6.560728,A019,Escherichia coli,urine,Commensal strain,2,0.125819,1.257749,0.121310,0.505074,0.085845,1.423255,2
48,5.112294,3.986432,A049,Escherichia coli,blood,Commensal strain,2,0.068078,1.466022,0.065118,0.484535,0.000000,1.634570,0
47,3.021666,7.141584,A048,Escherichia coli,urine,Pathogenic strain,2,0.000000,0.295724,0.000000,0.000000,0.000000,0.000000,6
46,5.020254,8.567518,A047,Escherichia coli,blood,Pathogenic strain,2,0.059151,0.768701,0.053085,0.386740,0.062916,0.721458,7
41,6.832757,7.503795,A042,Escherichia coli,animal,Commensal strain,2,0.063002,1.099966,0.059168,0.698869,0.468158,1.496427,4
35,6.915292,6.583098,A036,Escherichia coli,urine,Pathogenic strain,2,0.061489,0.847877,0.065874,0.474316,0.135198,1.276985,4
34,4.657805,5.734182,A035,Escherichia coli,blood,Pathogenic strain,2,0.090453,0.358145,0.091277,0.602020,0.128149,0.356802,9
33,5.388848,8.466379,A034,Escherichia coli,urine,Pathogenic strain,2,0.148468,1.514931,0.174638,0.964351,0.281844,1.799167,7
28,3.780450,5.376362,A029,Escherichia coli,urine,Pathogenic strain,2,0.038148,0.454360,0.041360,0.181459,0.063350,0.410762,8
27,7.065422,5.343500,A028,Escherichia coli,urine,Pathogenic strain,2,0.063728,0.469590,0.060516,0.462755,0.241647,0.335668,9
1,2.833671,6.823800,A002,Escherichia coli,blood,Pathogenic strain,2,0.098481,0.964883,0.110471,0.233285,0.000000,1.403835,6
24,5.788682,4.119866,A025,Escherichia coli,urine,Pathogenic strain,2,0.116096,1.069537,0.105668,0.409785,0.086824,1.458853,0
21,7.502212,6.049275,A022,Escherichia coli,urine,Pathogenic strain,2,0.101257,1.376189,0.098314,0.589933,0.203312,1.252159,1
20,2.310514,4.258615,A021,Escherichia coli,urine,Pathogenic strain,2,0.061584,0.950317,0.075575,0.313006,0.162490,0.894661,3
19,8.049274,5.591848,A020,Escherichia coli,animal,Pathogenic strain,2,0.082608,1.442216,0.085339,0.623049,0.475105,1.357744,1
25,6.135004,7.595472,A026,Escherichia coli,urine,Pathogenic strain,2,0.080601,0.402158,0.077426,0.414082,0.103131,0.519733,7
49,6.964060,6.230907,A050,Escherichia coli,blood,Pathogenic strain,2,0.085828,0.498012,0.085823,0.406485,0.400230,0.804463,1
15,7.538784,6.070635,A016,Escherichia coli,urine,Pathogenic strain,2,0.072720,0.937760,0.068781,0.423892,0.047651,0.923642,1
3,5.030077,4.642758,A004,Escherichia coli,feces,Pathogenic strain,2,0.116999,1.080682,0.101199,0.655379,0.305054,1.441512,0
12,5.605287,8.474524,A013,Escherichia coli,animal,Commensal strain,2,0.028711,1.005421,0.029881,0.519286,0.102004,0.956556,7
5,8.601402,5.937885,A006,Escherichia coli,blood,Commensal strain,2,0.059154,0.440163,0.055266,0.626941,0.399951,0.318405,1
10,6.978213,5.417409,A011,Escherichia coli,urine,Pathogenic strain,2,0.066525,0.360219,0.057416,0.330000,0.042813,0.207323,9
42,5.142991,4.475378,A043,Escherichia coli,animal,Commensal strain,1,0.027601,1.143011,0.024973,0.587101,0.412273,1.441764,0
37,2.637517,4.127516,A038,Escherichia coli,animal,Commensal strain,1,0.064158,0.361581,0.054835,0.848437,0.866862,0.264537,3
38,6.772678,7.540791,A039,Escherichia coli,animal,Commensal strain,1,NaN,1.017625,0.852120,0.986102,1.471669,1.512971,4
39,2.754321,5.394068,A040,Escherichia coli,animal,Commensal strain,1,NaN,0.474561,0.000000,0.418395,0.000000,0.756904,6
40,7.452787,6.422853,A041,Escherichia coli,animal,Commensal strain,1,0.090609,1.060518,0.075027,0.619777,0.614616,0.849139,1
43,4.572856,3.687471,A044,Escherichia coli,animal,Commensal strain,1,0.046493,1.085507,0.043165,0.516218,0.311859,1.140670,0
6,7.017246,8.315863,A007,Escherichia coli,feces,Commensal strain,1,0.065956,0.410300,0.072963,0.665995,0.000000,0.682995,5
44,6.550695,5.065118,A045,Escherichia coli,animal,Commensal strain,1,0.028830,1.370487,0.015348,0.751111,0.262701,1.571381,9
45,4.764575,6.896369,A046,Escherichia coli,blood,Commensal strain,1,0.038908,0.200962,0.036836,0.528246,0.164302,0.463759,2
4,2.691040,4.057780,A005,Escherichia coli,feces,Commensal strain,1,0.101523,0.272807,0.120601,0.186437,0.121745,0.398072,3
2,3.178256,5.519982,A003,Escherichia coli,blood,Commensal strain,1,0.066501,0.498872,0.061445,0.564547,0.313546,0.368546,8
36,6.638712,5.152672,A037,Escherichia coli,animal,Commensal strain,1,0.000000,1.123975,0.000000,0.570495,0.000000,1.310924,9
17,5.642871,4.021120,A018,Escherichia coli,blood,Commensal strain,1,0.059517,1.287046,0.058336,0.518358,0.326629,1.497189,0
7,6.423557,8.646023,A008,Escherichia coli,blood,Commensal strain,1,0.097187,1.166485,0.095053,0.669338,0.333712,1.242928,5
16,2.329631,6.700236,A017,Escherichia coli,animal,Commensal strain,1,0.110548,1.289325,0.110910,0.659531,0.339610,1.570828,6
32,8.455470,6.502862,A033,Escherichia coli,animal,Commensal strain,1,0.045629,0.282114,0.053033,1.034223,0.746827,0.224086,1
31,5.257375,5.715269,A032,Escherichia coli,blood,Commensal strain,1,1.133788,1.048136,1.119326,0.584882,0.495628,0.709660,2
30,3.480180,5.646476,A031,Escherichia coli,animal,Commensal strain,1,0.167967,0.617078,0.161436,0.467293,0.392423,0.621435,3
29,3.714443,5.799578,A030,Escherichia coli,blood,Commensal strain,1,0.076548,0.398078,0.071058,0.736091,0.653928,0.365928,6
9,5.572557,5.726862,A010,Escherichia coli,feces,Commensal strain,1,0.049851,0.307426,0.053692,0.656571,0.669971,0.544498,2
26,7.637985,6.490184,A027,Escherichia coli,animal,Commensal strain,1,0.040250,1.407527,0.040860,0.584192,0.000000,1.490921,1
11,2.120512,3.840546,A012,Escherichia coli,animal,Commensal strain,1,0.199173,1.395184,0.164683,0.579315,0.202552,1.442600,3
23,4.709624,4.452234,A024,Escherichia coli,blood,Commensal strain,1,0.055793,0.449640,0.053833,0.571760,0.243998,0.817029,0
22,3.740108,4.893625,A023,Escherichia coli,animal,Commensal strain,1,0.101257,0.407429,0.077279,0.661731,0.487289,0.412373,8
13,8.125718,6.337743,A014,Escherichia coli,animal,Commensal strain,1,0.040533,1.257316,0.033206,0.573845,0.167805,1.242958,1
14,5.373610,6.328361,A015,Escherichia coli,feces,Commensal strain,1,0.228693,1.327152,0.225516,0.722939,0.429100,1.258443,2
8,3.903013,6.026175,A009,Escherichia coli,feces,Commensal strain,1,NaN,0.847180,0.051094,0.518218,0.127822,0.548859,2

In [198]:
# Part 8: Groups Analysis
# the mean of cipro_fit grouped by label type
print('Mean of cipro_fit by labels:')
bacteria_data.groupby('labels')['cipro_fit'].mean()

Mean of cipro_fit by labels:

labels
0    0.064613
1    0.063612
2    0.267962
3    0.115426
4    0.325721
5    0.084008
6    0.058488
7    0.083757
8    0.060028
9    0.044911
Name: cipro_fit, dtype: float64

In [199]:
# the mean of carb_fit grouped by label type
print('Mean of carb_fit by labels:')
bacteria_data.groupby('labels')['carb_fit'].mean()

Mean of carb_fit by labels:

labels
0    1.083064
1    0.953535
2    0.831434
3    0.719393
4    0.988490
5    0.788392
6    0.684514
7    0.922803
8    0.453554
9    0.736483
Name: carb_fit, dtype: float64

In [200]:
# the maximum of cipro_fit grouped by label type
print('Max of cipro_fit by labels:')
bacteria_data.groupby('labels')['cipro_fit'].max()

Max of cipro_fit by labels:

labels
0    0.105668
1    0.098314
2    1.119326
3    0.164683
4    0.852120
5    0.095053
6    0.110910
7    0.174638
8    0.077279
9    0.091277
Name: cipro_fit, dtype: float64

In [201]:
# the maximum of carb_fit grouped by label type
print('Max of carb_fit by labels:')
bacteria_data.groupby('labels')['carb_fit'].max()

Max of carb_fit by labels:

labels
0    1.466022
1    1.442216
2    1.327152
3    1.395184
4    1.099966
5    1.166485
6    1.289325
7    1.514931
8    0.498872
9    1.370487
Name: carb_fit, dtype: float64

In [202]:
# Count how many rows belong to each Phenotype
print('Count per Phenotype:')
bacteria_data['Phenotype'].value_counts()

Count per Phenotype:

Phenotype
Commensal strain     32
Pathogenic strain    18
Name: count, dtype: int64